// Generates public/styles.css for the static pages (login, help, checkout,
// lp-*, policy pages — 35 files link /styles.css) from the SPA's stylesheets,
// in the same order src/styles/global.css imports them. Keeps the static
// shell pixel-identical to the SPA without hand-maintaining a second
// stylesheet. Runs as part of `npm run build` (and `npm run dev`).
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const globalCss = readFileSync(join(root, "src/styles/global.css"), "utf8");

const imports = [...globalCss.matchAll(/@import\s+"\.\/([^"]+)"/g)].map((m) => m[1]);
if (imports.length === 0) {
  console.error("build_styles: no @import entries found in src/styles/global.css");
  process.exit(1);
}

const banner =
  "/* GENERATED by scripts/build_styles.mjs from src/styles/* — do not edit.\n" +
  "   Shared stylesheet for the static pages in public/. */\n";
const parts = imports.map(
  (file) => `/* ===== src/styles/${file} ===== */\n` + readFileSync(join(root, "src/styles", file), "utf8"),
);
const out = banner + parts.join("\n");

writeFileSync(join(root, "public/styles.css"), out);
console.log(`build_styles: wrote public/styles.css (${out.length} bytes from ${imports.join(", ")})`);
